#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNeptuno
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="neptuno")]
	public partial class DataNeptunoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEmpleados(Empleados instance);
    partial void UpdateEmpleados(Empleados instance);
    partial void DeleteEmpleados(Empleados instance);
    partial void Insertcategorias(categorias instance);
    partial void Updatecategorias(categorias instance);
    partial void Deletecategorias(categorias instance);
    #endregion
		
		public DataNeptunoDataContext() : 
				base(global::ProyectoNeptuno.Properties.Settings.Default.neptunoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataNeptunoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNeptunoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNeptunoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataNeptunoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empleados> Empleados
		{
			get
			{
				return this.GetTable<Empleados>();
			}
		}
		
		public System.Data.Linq.Table<categorias> categorias
		{
			get
			{
				return this.GetTable<categorias>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmpleado;
		
		private string _Apellidos;
		
		private string _Nombre;
		
		private string _cargo;
		
		private string _Tratamiento;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private System.Nullable<System.DateTime> _FechaContratacion;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _region;
		
		private string _codPostal;
		
		private string _pais;
		
		private string _TelDomicilio;
		
		private string _Extension;
		
		private string _notas;
		
		private System.Nullable<int> _Jefe;
		
		private System.Nullable<decimal> _sueldoBasico;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpleadoChanging(int value);
    partial void OnIdEmpleadoChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OncargoChanging(string value);
    partial void OncargoChanged();
    partial void OnTratamientoChanging(string value);
    partial void OnTratamientoChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OnFechaContratacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaContratacionChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncodPostalChanging(string value);
    partial void OncodPostalChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    partial void OnTelDomicilioChanging(string value);
    partial void OnTelDomicilioChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnnotasChanging(string value);
    partial void OnnotasChanged();
    partial void OnJefeChanging(System.Nullable<int> value);
    partial void OnJefeChanged();
    partial void OnsueldoBasicoChanging(System.Nullable<decimal> value);
    partial void OnsueldoBasicoChanged();
    #endregion
		
		public Empleados()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					this.OnIdEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdEmpleado = value;
					this.SendPropertyChanged("IdEmpleado");
					this.OnIdEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(20)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(40)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this.OncargoChanging(value);
					this.SendPropertyChanging();
					this._cargo = value;
					this.SendPropertyChanged("cargo");
					this.OncargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tratamiento", DbType="VarChar(40)")]
		public string Tratamiento
		{
			get
			{
				return this._Tratamiento;
			}
			set
			{
				if ((this._Tratamiento != value))
				{
					this.OnTratamientoChanging(value);
					this.SendPropertyChanging();
					this._Tratamiento = value;
					this.SendPropertyChanged("Tratamiento");
					this.OnTratamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaContratacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaContratacion
		{
			get
			{
				return this._FechaContratacion;
			}
			set
			{
				if ((this._FechaContratacion != value))
				{
					this.OnFechaContratacionChanging(value);
					this.SendPropertyChanging();
					this._FechaContratacion = value;
					this.SendPropertyChanged("FechaContratacion");
					this.OnFechaContratacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(60)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(15)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(15)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPostal", DbType="VarChar(10)")]
		public string codPostal
		{
			get
			{
				return this._codPostal;
			}
			set
			{
				if ((this._codPostal != value))
				{
					this.OncodPostalChanging(value);
					this.SendPropertyChanging();
					this._codPostal = value;
					this.SendPropertyChanged("codPostal");
					this.OncodPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(15)")]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this.OnpaisChanging(value);
					this.SendPropertyChanging();
					this._pais = value;
					this.SendPropertyChanged("pais");
					this.OnpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelDomicilio", DbType="VarChar(24)")]
		public string TelDomicilio
		{
			get
			{
				return this._TelDomicilio;
			}
			set
			{
				if ((this._TelDomicilio != value))
				{
					this.OnTelDomicilioChanging(value);
					this.SendPropertyChanging();
					this._TelDomicilio = value;
					this.SendPropertyChanged("TelDomicilio");
					this.OnTelDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="VarChar(4)")]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notas", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string notas
		{
			get
			{
				return this._notas;
			}
			set
			{
				if ((this._notas != value))
				{
					this.OnnotasChanging(value);
					this.SendPropertyChanging();
					this._notas = value;
					this.SendPropertyChanged("notas");
					this.OnnotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jefe", DbType="Int")]
		public System.Nullable<int> Jefe
		{
			get
			{
				return this._Jefe;
			}
			set
			{
				if ((this._Jefe != value))
				{
					this.OnJefeChanging(value);
					this.SendPropertyChanging();
					this._Jefe = value;
					this.SendPropertyChanged("Jefe");
					this.OnJefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sueldoBasico", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sueldoBasico
		{
			get
			{
				return this._sueldoBasico;
			}
			set
			{
				if ((this._sueldoBasico != value))
				{
					this.OnsueldoBasicoChanging(value);
					this.SendPropertyChanging();
					this._sueldoBasico = value;
					this.SendPropertyChanged("sueldoBasico");
					this.OnsueldoBasicoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categorias")]
	public partial class categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcategoria;
		
		private string _nombrecategoria;
		
		private string _descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcategoriaChanging(int value);
    partial void OnidcategoriaChanged();
    partial void OnnombrecategoriaChanging(string value);
    partial void OnnombrecategoriaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public categorias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idcategoria
		{
			get
			{
				return this._idcategoria;
			}
			set
			{
				if ((this._idcategoria != value))
				{
					this.OnidcategoriaChanging(value);
					this.SendPropertyChanging();
					this._idcategoria = value;
					this.SendPropertyChanged("idcategoria");
					this.OnidcategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecategoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombrecategoria
		{
			get
			{
				return this._nombrecategoria;
			}
			set
			{
				if ((this._nombrecategoria != value))
				{
					this.OnnombrecategoriaChanging(value);
					this.SendPropertyChanging();
					this._nombrecategoria = value;
					this.SendPropertyChanged("nombrecategoria");
					this.OnnombrecategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
